### ISSUE TITLE
运行起来后发现变形，请教下这怎么处理😢

### ISSUE THREAD

**Issue by chana1024** [Ewall1106/vue-h5-template#10]
![image](https://user-images.githubusercontent.com/62974111/126097903-be9b9e86-cd58-410e-a630-109db2c6e745.png)
运行起来后发现变形，请教下这怎么处理😢

**Comment by 2601940602** [comment]
同变形，vant的组件都变形了

**Comment by 2601940602** [comment]
![image](https://user-images.githubusercontent.com/31914597/128693433-881f4c5d-4069-4e3a-a220-dc2c94a9e34a.png)
添加不转换路径
exclude: /(\/|\\)(node_modules)(\/|\\)/

**Comment by Ewall1106** [comment]
> ![image](https://user-images.githubusercontent.com/62974111/126097903-be9b9e86-cd58-410e-a630-109db2c6e745.png)
> 运行起来后发现变形，请教下这怎么处理😢

已修复[hotfix：修复样式变形问题](https://github.com/Ewall1106/vue-h5-template/commit/198bf5ba466fcfc696c8975213c81ce5693ff230)
