### ISSUE TITLE
控制台报ts错

### ISSUE THREAD

**Issue by lovehebe330** [Ewall1106/vue-h5-template#11]
![image](https://user-images.githubusercontent.com/20655248/130021349-46f1f90f-7a3e-464a-ba3d-d4fd4dc0db65.png)
![image](https://user-images.githubusercontent.com/20655248/130021450-b84e7e96-57df-4021-82d6-e5de9024f83a.png)
![image](https://user-images.githubusercontent.com/20655248/130021498-1762167f-4f4b-4793-8f7c-ef18124f99fa.png)
![image](https://user-images.githubusercontent.com/20655248/130021549-838f7ac7-d0e1-40fa-a60f-a68594506cd8.png)

bz不知道为什么控制太突然爆ts的错误 删除掉node_modules库再重新安装也没有效果， 这个要如何解决

**Comment by Ewall1106** [comment]
> ![image](https://user-images.githubusercontent.com/20655248/130021349-46f1f90f-7a3e-464a-ba3d-d4fd4dc0db65.png)
> ![image](https://user-images.githubusercontent.com/20655248/130021450-b84e7e96-57df-4021-82d6-e5de9024f83a.png)
> ![image](https://user-images.githubusercontent.com/20655248/130021498-1762167f-4f4b-4793-8f7c-ef18124f99fa.png)
> ![image](https://user-images.githubusercontent.com/20655248/130021549-838f7ac7-d0e1-40fa-a60f-a68594506cd8.png)
> 
> bz不知道为什么控制太突然爆ts的错误 删除掉node_modules库再重新安装也没有效果， 这个要如何解决

拉下最新的master分支，代码已经更新了。
