### ISSUE TITLE
应用启动时报错

### ISSUE THREAD

**Issue by kingfront** [Ewall1106/vue-h5-template#8]
ERROR  Failed to compile with 1 error                                                                                                               14:53:27

 error  in ./node_modules/vant/es/toast/index.css

TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Array.map (<anonymous>)

 @ ./node_modules/vant/es/toast/style/index.js 7:0-22
 @ ./src/utils/permission.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Ewall1106** [comment]
要不你重新安装试一下？我刚刚重装跑了一下没发现问题。

**Comment by Ewall1106** [comment]
> ERROR Failed to compile with 1 error 14:53:27
> 
> error in ./node_modules/vant/es/toast/index.css
> 
> TypeError: Cannot read property 'prefix_exceptions' of undefined
> at Array.map ()
> 
> @ ./node_modules/vant/es/toast/style/index.js 7:0-22
> @ ./src/utils/permission.ts
> @ ./src/main.ts
> @ multi ./src/main.ts
> ERROR Build failed with errors.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
要不你重新安装试一下？我刚刚重装跑了一下没发现问题。

**Comment by kingfront** [comment]
重新安装一下可以了，之前也尝试过重新安装的，这次可以啦，谢谢！
